# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Tae
tagline:          
description:      'Aspiring Software Engineer'
url:              https://hey-tae.github.io/
baseurl:          /

author:
  name:           'Tae Wilson'
  url:            https://twitter.com/taevstheworld

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hey-tae/hey-tae.github.io
